import { DM_Sans } from 'next/font/google'

import './globals.css'
import Navbar from '@/compunents/navbar/Navbar'
import Provider from '@/context/Provider'

const work = DM_Sans({ subsets: ['latin'], weight:"500"})

export const metadata = {
  title: 'Vaspitna',
  description: 'Generated by @xhemo',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">

      <body className={work.className}>
        <Provider>
          <div className='contanier'>
           <Navbar/>
            {children}
          </div>
        </Provider>


      </body>
    </html>
  )
}
